name: Build & Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.6.0
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 22
      - run: corepack enable

      - name: Install
        shell: bash
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint
