name: push docker image

on:
  push:
    branches:
      - "main"

jobs:
  build_and_push:
    name: build_and_push (${{ matrix.docker.repo }})
    strategy:
      matrix:
        docker:
          - repo: planetariumhq/9c-rudolf
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: login
        run: |
          docker login \
            --username '${{ secrets.DOCKER_USERNAME }}' \
            --password '${{ secrets.DOCKER_ACCESS_TOKEN }}'
      - name: setup-qemu
        run: |
          docker run --rm --privileged multiarch/qemu-user-static \
            --reset \
            -p yes
      - name: build-and-push
        run: |
          docker buildx build . \
            --platform linux/arm64v8,linux/amd
          docker push ${{ matrix.docker.repo }}:git-${{ github.sha }}
